profile::docker::engine::declare_service: true
profile::docker::engine::packagename: docker.io
profile::docker::engine::settings: {}
profile::docker::engine::version: 18.09.1+dfsg1-7.1+deb10u2
profile::docker::runner::service_defs:
  mediawiki-services-mobileapps:
    config:
      logging:
        level: warn
        name: mobileapps
        streams:
        - host: deployment-logstash03.deployment-prep.eqiad.wmflabs
          port: 12201
          type: gelf
        - type: stdout
      metrics:
        host: prometheus-labmon.eqiad.wmnet
        name: mobileapps
        port: 8125
        type: statsd
      num_workers: ncpu * 1.5
      services:
      - conf:
          cors: '*'
          mobile_html_csp: 'default-src ''none''; connect-src app://*.wikipedia.org
            https://*.wikipedia.org; media-src app://upload.wikimedia.org https://upload.wikimedia.org
            ''self''; img-src app://*.wikimedia.org https://*.wikimedia.org app://wikimedia.org
            https://wikimedia.org ''self'' data:; object-src ''none''; script-src
            app://meta.wikimedia.org https://meta.wikimedia.org ''unsafe-inline'';
            style-src app://meta.wikimedia.org https://meta.wikimedia.org app://*.wikipedia.org
            https://*.wikipedia.org ''self'' ''unsafe-inline''; frame-ancestors ''self'' '
          mobile_html_local_rest_api_base_uri_template: //{{domain}}/api/rest_v1/
          mobile_html_rest_api_base_uri: //meta.wikimedia.org/api/rest_v1/
          mw_resource_loader_req:
            body: '{{ default(request.query, {}) }}'
            headers:
              host: '{{request.params.domain}}'
              user-agent: '{{user-agent}}'
            method: post
            uri: http://deployment-mediawiki11.deployment-prep.eqiad1.wikimedia.cloud/w/load.php
          mwapi_req:
            body: '{{ default(request.query, {}) }}'
            headers:
              accept-language: '{{accept-language}}'
              host: '{{request.params.domain}}'
              user-agent: '{{user-agent}}'
            method: post
            uri: http://deployment-mediawiki11.deployment-prep.eqiad1.wikimedia.cloud/w/api.php
          port: 8888
          restbase_compatibility:
            security_headers: false
          restbase_req:
            body: '{{request.body}}'
            headers: '{{request.headers}}'
            method: '{{request.method}}'
            query: '{{ default(request.query, {}) }}'
            timeout: 60000
            uri: http://deployment-restbase04.deployment-prep.eqiad1.wikimedia.cloud:7231/{{domain}}/v1/{+path}
          user_agent: Mobile-Content-Service/WMF
        module: ./app.js
        name: mobileapps
      startup_concurrency: 4
      worker_heap_limit_mb: 750
      worker_heartbeat_timeout: 15000
    namespace: wikimedia
    override_cmd: -c /etc/mediawiki-services-mobileapps/config.yaml
    port: 8888
    version: 2023-01-31-130212-production
