profile::nginx::variant: full
profile::query_service::blazegraph_extra_jvm_opts:
- -Dwdqs.throttling-filter.time-bucket-capacity-in-seconds=240
profile::query_service::blazegraph_heap_size: 4g
profile::query_service::blazegraph_options:
- -XX:+ExitOnOutOfMemoryError
profile::query_service::data_dir: /srv/wdqs
profile::query_service::deploy_mode: manual
profile::query_service::deploy_name: wdqs
profile::query_service::endpoint: http://test.query.org
profile::query_service::log_dir: /var/log/wdqs
profile::query_service::nodes:
- deployment-wdqs01.deployment-prep.eqiad.wmflabs
profile::query_service::oauth: false
profile::query_service::package_dir: /srv/deployment/wdqs/wdqs
profile::query_service::updater_options: -n wdq
profile::query_service::use_revisions: false
puppetmaster: deployment-puppetmaster04.deployment-prep.eqiad.wmflabs
