profile::docker::engine::declare_service: true
profile::docker::engine::settings: {}
profile::docker::engine::version: 1.12.6-0~debian-jessie
profile::docker::runner::service_defs:
  mediawiki-services-wikifeeds:
    config:
      logging:
        level: trace
      metrics: {}
      num_workers: 0
      services:
      - conf:
          cors: '*'
          mw_req:
            headers:
              accept-language: '{{accept-language}}'
              user-agent: '{{user-agent}}'
            method: get
            query:
              title: '{{request.params.title}}'
            uri: http://deployment-mediawiki11.deployment-prep.eqiad1.wikimedia.cloud/w/index.php
          mwapi_req:
            body: '{{ default(request.query, {}) }}'
            headers:
              accept-language: '{{accept-language}}'
              host: '{{request.params.domain}}'
              user-agent: '{{user-agent}}'
            method: post
            uri: http://deployment-mediawiki11.deployment-prep.eqiad1.wikimedia.cloud/w/api.php
          port: 8889
          restbase_req:
            body: '{{request.body}}'
            headers: '{{request.headers}}'
            method: '{{request.method}}'
            query: '{{ default(request.query, {}) }}'
            uri: http://deployment-restbase04.deployment-prep.eqiad1.wikimedia.cloud:7231/{{domain}}/v1/{+path}
          user_agent: WMF Wikifeeds beta
        module: ./app.js
        name: wikifeeds
    namespace: wikimedia
    override_cmd: -c /etc/mediawiki-services-wikifeeds/config.yaml
    port: 8889
    version: 2023-03-23-165924-production
puppetmaster: deployment-puppetmaster04.deployment-prep.eqiad.wmflabs
