labspuppetbackend_mysql_password: notset
profile::eventlogging::analytics::mysql::consumers:
- mysql-m4-master-00
profile::eventlogging::analytics::mysql::statsd_host: prometheus-labmon.eqiad.wmnet
profile::eventlogging::analytics::processor::kafka_producer_scheme: kafka-confluent://
profile::eventlogging::analytics::server::kafka_cluster: jumbo
profile::eventlogging::analytics::server::python_kafka_version: 1.4.7-1
profile::mariadb::misc::eventlogging::database::master: true
profile::mariadb::misc::eventlogging::database::shard: m4
