profile::configmaster::server_aliases: []
profile::configmaster::server_name: config-master.wikimedia.beta.wmflabs.org
profile::puppet::agent::force_puppet7: true
profile::puppetmaster::common::puppetdb_host: deployment-puppetdb05.deployment-prep.eqiad1.wikimedia.cloud
profile::puppetmaster::common::puppetdb_hosts:
- deployment-puppetdb05.deployment-prep.eqiad1.wikimedia.cloud
profile::puppetserver::extra_mounts:
  volatile: /srv/puppet_fileserver/volatile
profile::puppetserver::java_max_mem: 7g
profile::puppetserver::puppetdb_urls:
- https://deployment-puppetdb05.deployment-prep.eqiad1.wikimedia.cloud
profile::puppetserver::volatile::ip_reputation_config: {}
profile::services_proxy::envoy::ensure: absent
profile::ssh::ca::ca_key_id: deployment-prep SSH CA key v1
profile::ssh::ca::ca_key_secret: ssh/ca/ssh-ca
profile::ssh::ca::ensure: present
profile::tlsproxy::envoy::access_log: true
profile::tlsproxy::envoy::capitalize_headers: true
profile::tlsproxy::envoy::cfssl_options:
  hosts:
  - '%{facts.fqdn}'
  - config-master
  - config-master.wikimedia.beta.wmflabs.org
profile::tlsproxy::envoy::ensure: present
profile::tlsproxy::envoy::global_cert_name: '%{facts.fqdn}'
profile::tlsproxy::envoy::retries: false
profile::tlsproxy::envoy::services:
- port: 80
  server_names:
  - '*'
profile::tlsproxy::envoy::sni_support: 'no'
profile::tlsproxy::envoy::ssl_provider: cfssl
profile::tlsproxy::envoy::tls_port: 443
profile::tlsproxy::envoy::upstream_response_timeout: 203.0
puppetmaster: deployment-puppetserver-1.deployment-prep.eqiad1.wikimedia.cloud
