profile::base::certificates::include_bundle_jks: true
profile::java::java_packages:
- variant: jdk
  version: '8'
profile::kafka::broker::auth_acls_enabled: false
profile::kafka::broker::group_initial_rebalance_delay: 10000
profile::kafka::broker::inter_broker_protocol_version: 1.1.0
profile::kafka::broker::kafka_cluster_name: logging-eqiad
profile::kafka::broker::max_heap_size: 2g
profile::kafka::broker::monitoring::is_critical: true
profile::kafka::broker::monitoring_enabled: true
profile::kafka::broker::num_io_threads: 4
profile::kafka::broker::num_partitions: 6
profile::kafka::broker::num_recovery_threads_per_data_dir: 4
profile::kafka::broker::num_replica_fetchers: 4
profile::kafka::broker::ssl_enabled: true
profile::kafka::broker::ssl_password: qwerty
