profile::envoy::ensure: present
profile::mediawiki::mcrouter_wancache::use_onhost_memcached: true
profile::mediawiki::webserver::has_tls: true
profile::pki::client::ensure: present
profile::rsyslog::kafka_shipper::json_lines_port: 10514
profile::rsyslog::kafka_shipper::kafka_brokers:
- deployment-kafka-logging01.deployment-prep.eqiad1.wikimedia.cloud:9093
profile::services_proxy::envoy::ensure: absent
profile::tlsproxy::envoy::access_log: true
profile::tlsproxy::envoy::capitalize_headers: true
profile::tlsproxy::envoy::cfssl_label: discovery
profile::tlsproxy::envoy::cfssl_options:
  hosts:
  - appservers.svc.deployment-prep.eqiad1.wikimedia.cloud
  - api.svc.deployment-prep.eqiad1.wikimedia.cloud
  - '*.wikipedia.beta.wmflabs.org'
  - '*.wiktionary.beta.wmflabs.org'
  - '*.wikibooks.beta.wmflabs.org'
  - '*.wikinews.beta.wmflabs.org'
  - '*.wikiquote.beta.wmflabs.org'
  - '*.wikisource.beta.wmflabs.org'
  - '*.wikiversity.beta.wmflabs.org'
  - '*.wikivoyage.beta.wmflabs.org'
  - '*.wikimedia.beta.wmflabs.org'
  - '*.wikifunctions.beta.wmflabs.org'
  - '*.m.wikipedia.beta.wmflabs.org'
  - '*.m.wiktionary.beta.wmflabs.org'
  - '*.m.wikibooks.beta.wmflabs.org'
  - '*.m.wikinews.beta.wmflabs.org'
  - '*.m.wikiquote.beta.wmflabs.org'
  - '*.m.wikisource.beta.wmflabs.org'
  - '*.m.wikiversity.beta.wmflabs.org'
  - '*.m.wikivoyage.beta.wmflabs.org'
  - '*.m.wikifunctions.beta.wmflabs.org'
  - '*.m.wikimedia.beta.wmflabs.org'
  - wikidata.beta.wmflabs.org
  - wikifunctions.beta.wmflabs.org
profile::tlsproxy::envoy::ensure: present
profile::tlsproxy::envoy::global_cert_name: appservers.svc.deployment-prep.eqiad1.wikimedia.cloud
profile::tlsproxy::envoy::retries: false
profile::tlsproxy::envoy::services:
- port: 80
  server_names:
  - '*'
profile::tlsproxy::envoy::sni_support: 'no'
profile::tlsproxy::envoy::ssl_provider: cfssl
profile::tlsproxy::envoy::tls_port: 443
profile::tlsproxy::envoy::upstream_response_timeout: 203.0
