profile::docker::engine::declare_service: true
profile::docker::engine::packagename: docker.io
profile::docker::engine::settings: {}
profile::docker::runner::service_defs:
  mediawiki-services-cxserver:
    config:
      logging:
        level: trace
        name: cxserver
        streams:
        - host: deployment-logstash03.deployment-prep.eqiad.wmflabs
          port: 12201
          type: gelf
        - type: stdout
        - level: trace
          path: /etc/mediawiki-services-cxserver/main.log
          type: file
      metrics:
        host: prometheus-labmon.eqiad.wmnet
        name: cxserver
        port: 8125
        type: statsd
      num_workers: ncpu
      ratelimiter:
        listen:
          address: 127.0.0.1
          port: 3051
        seeds:
        - 127.0.0.1
        type: kademlia
      services:
      - conf:
          cors: '*'
          dictionary:
            JsonDict:
              languages: /srv/service/config/JsonDict.yaml
          jwt:
            algorithms:
            - HS256
            secret: H.9F-.|,SC#Von%?Tklo"a<uPFOcxI$>
          languages: /srv/service/config/languages.yaml
          mt:
            Apertium:
              api: http://apertium-beta.wmflabs.org
              languages: /srv/service/config/Apertium.wikimedia.yaml
            Google:
              api: https://www.googleapis.com/language/translate/v2
              key: dummykey
              languages: /srv/service/config/Google.yaml
            LingoCloud:
              account: wikimedia
              api: https://api.interpreter.caiyunai.com/v1
              key: dummykey
              languages: /srv/service/config/LingoCloud.yaml
            Matxin:
              api: http://matxin.elhuyar.eus/API
              key: dummykey
              languages: /srv/service/config/Matxin.yaml
            TestClient:
              languages: /srv/service/config/TestClient.yaml
            Yandex:
              api: https://translate.yandex.net
              key: trnsl.1.1.20150216T113622Z.2ccb71d878ea0b58.5ac57322acecfa2d9001aad077fdcff21c206a43
              languages: /srv/service/config/Yandex.yaml
            Youdao:
              api: https://openapi.youdao.com/api
              appKey: dummykey
              appSecret: dummysecret
              languages: /srv/service/config/Youdao.yaml
            defaults: /srv/service/config/mt-defaults.wikimedia.yaml
          mw_host: en.wikipedia.beta.wmflabs.org
          mwapi_req:
            body: '{{request.body}}'
            headers:
              host: '{{request.params.domain}}'
              user-agent: '{{user-agent}}'
            method: post
            query: '{{ default(request.query, {}) }}'
            uri: http://deployment-mediawiki11.deployment-prep.eqiad1.wikimedia.cloud/w/api.php
          no_proxy_list:
          - wmflabs
          port: 8080
          proxy: null
          ratelimiter_key: X-Client-IP
          ratelimiter_rate: 10
          restbase_req:
            body: '{{request.body}}'
            headers: '{{request.headers}}'
            method: '{{request.method}}'
            query: '{{ default(request.query, {}) }}'
            uri: http://deployment-restbase04.deployment-prep.eqiad1.wikimedia.cloud:7231/{{domain}}/v1/{+path}
          user_agent: CXServer/WMF
        module: ../app.js
        name: cxserver
      worker_heap_limit_mb: 300
      worker_heartbeat_timeout: 7500
    namespace: wikimedia
    override_cmd: -c /etc/mediawiki-services-cxserver/config.yaml
    port: 8080
    version: 2019-05-08-064536-production
puppetmaster: deployment-puppetmaster04.deployment-prep.eqiad.wmflabs
