profile::docker::engine::declare_service: true
profile::docker::engine::settings: {}
profile::docker::engine::version: 1.12.6-0~debian-jessie
profile::docker::runner::service_defs:
  mediawiki-services-mathoid:
    config:
      cors: '*'
      dpi: 180
      img: true
      mj_config:
        MathJax:
          SVG:
            font: TeX
          TeX:
            noErrors:
              disabled: true
          menuSettings:
            semantics: true
        extensions: TeX/color,TeX/mediawiki-texvc,TeX/mhchem
      mwapi_req:
        body: '{{ default(request.query, {}) }}'
        headers:
          host: '{{request.params.domain}}'
          user-agent: '{{user-agent}}'
        method: post
        uri: http://deployment-mediawiki11.deployment-prep.eqiad1.wikimedia.cloud/w/api.php
      no_check: true
      png: true
      port: 10044
      restbase_req:
        body: '{{request.body}}'
        headers: '{{request.headers}}'
        method: '{{request.method}}'
        query: '{{ default(request.query, {}) }}'
        uri: http://deployment-restbase04.deployment-prep.eqiad1.wikimedia.cloud:7231/{{domain}}/v1/{+path}
      speech: true
      speech_config:
        domain: mathspeak
        enrich: false
        minSTree: false
        semantic: false
        semantics: true
        speakText: true
        style: default
      speech_on: false
      svg: true
      svgo: false
      texvcinfo: true
    namespace: wikimedia
    port: 10044
    version: 2019-04-24-175758-production
puppetmaster: deployment-puppetmaster04.deployment-prep.eqiad.wmflabs
