profile::envoy::ensure: present
profile::ores::celery::queue_maxsize: 100
profile::ores::celery::workers: 4
profile::ores::logstash_host: localhost
profile::ores::web::workers: 8
profile::services_proxy::envoy::enabled_listeners:
- mwapi-async
